# Generated by Django 4.1.7 on 2023-02-23 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='fornecedor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id_pedido', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('especieDestinada', models.CharField(max_length=30)),
                ('preco', models.FloatField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name=255)),
                ('marca', models.CharField(max_length=50)),
                ('validade', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=11)),
                ('cpf', models.CharField(max_length=14)),
                ('senha', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracao', models.CharField(max_length=20)),
                ('local', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=30)),
                ('id_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='fornece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enderecodestino', models.CharField(max_length=70)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pedido')),
            ],
        ),
        migrations.AddConstraint(
            model_name='fornece',
            constraint=models.UniqueConstraint(fields=('id_cliente', 'id_pedido'), name='nique_id_cliente_id_pedido_combination'),
        ),
        migrations.AddConstraint(
            model_name='compra',
            constraint=models.UniqueConstraint(fields=('id_cliente', 'id_pedido'), name='unique_id_cliente_id_pedido_combination'),
        ),
    ]
